# Generated by Django 4.2.4 on 2023-08-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('dni', models.IntegerField()),
                ('ciudad', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=70)),
                ('categoría', models.CharField(max_length=70)),
                ('meses_garantia', models.IntegerField()),
                ('promocion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sucursal', models.IntegerField()),
                ('ciudad', models.CharField(max_length=30)),
                ('metros_cuadrados', models.IntegerField()),
            ],
        ),
    ]
