# Generated by Django 4.2.4 on 2023-08-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_clientes_cliente_rename_productos_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoría',
        ),
    ]
